# Dependencies
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - tables
  - autolink
highlighter: rouge

plugins:
  - jekyll-multiple-languages-plugin
baseurl: ""

# Permalinks
permalink: pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             4000
url:              http://multiple-select.wenzhixin.net.cn
encoding:         UTF-8

# Languages
languages: ["en", "zh-cn"]
languages_string: ["English", "简体中文"]

# Custom vars
current_version: 1.2.2
repo: https://github.com/wenzhixin/multiple-select
website: http://wenzhixin.net.cn
repos: http://repos.wenzhixin.net.cn
email: wenzhixin2010@gmail.com
master_zip: https://github.com/wenzhixin/multiple-select/archive/master.zip
